spring:
  redis:
    host: 127.0.0.1
    password: ''
    port: 6379
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: jeecg-boot
          uri: http://127.0.0.1:8080
          predicates:
          - Path=/jeecg-boot/sys/**,/jeecg-system/sys/**,/sys/**,/webSocketApi/**,/online/**,/message/**,/test/**,/api/**,/vxeSocket/**
        - id: jeecg-b
          uri: http://127.0.0.1:8080
          predicates:
          - Path=/jeecg-boot/api/**

management:
  endpoints:
    web:
      exposure:
        include: '*'